<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2997" started-at="2018-09-14T10:48:57Z" finished-at="2018-09-14T10:49:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2997" started-at="2018-09-14T10:48:57Z" finished-at="2018-09-14T10:49:00Z">
      <class name="suit.view_cart">
        <test-method status="PASS" signature="Setup()[pri:0, instance:suit.view_cart@2b552920]" name="Setup" is-config="true" duration-ms="1418" started-at="2018-09-14T16:18:55Z" finished-at="2018-09-14T16:18:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="userregistration()[pri:0, instance:suit.view_cart@2b552920]" name="userregistration" duration-ms="2965" started-at="2018-09-14T16:18:57Z" finished-at="2018-09-14T16:19:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at suit.view_cart.userregistration(view_cart.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userregistration -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:suit.view_cart@2b552920]" name="getResult" is-config="true" duration-ms="15" started-at="2018-09-14T16:19:00Z" finished-at="2018-09-14T16:19:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=userregistration status=FAILURE method=view_cart.userregistration()[pri:0, instance:suit.view_cart@2b552920] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:suit.view_cart@2b552920]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-09-14T16:19:00Z" finished-at="2018-09-14T16:19:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- suit.view_cart -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
